name: circle_gadget
description: A flutter package which provides a circular gadget
version: 1.0.1
homepage: https://github.com/MarioJunio/flutter-circle-gadget

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: